services:

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile

    expose:
      - "5000"

    restart: always



  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productsdb

    expose:
      - "5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 10



  flyway:
    image: flyway/flyway

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      -url=jdbc:postgresql://postgres:5432/productsdb
      -user=admin
      -password=admin123
      migrate

    volumes:
      - ./database/migration:/flyway/sql



  redis:
    image: redis:7

    expose:
      - "6379"

    volumes:
      - redis-data:/data

    restart: always



  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile

    expose:
      - "5001"

    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: productsdb
      REDIS_HOST: redis

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    restart: always



  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - auth-service
      - product-service

    restart: always



volumes:
  postgres-data:
  redis-data:
