services:

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile

    container_name: auth-service

    ports:
      - "5500:5000"

    restart: always

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3



  postgres:
    image: postgres:15

    container_name: postgres-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productsdb

    ports:
      - "5435:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 10



  flyway:
    image: flyway/flyway

    container_name: flyway

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      -url=jdbc:postgresql://postgres:5432/productsdb
      -user=admin
      -password=admin123
      migrate

    volumes:
      - ./database/migration:/flyway/sql



  redis:
    image: redis:7

    container_name: redis-cache

    ports:
      - "6380:6379"

    volumes:
      - redis-data:/data

    restart: always

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5



  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile

    container_name: product-service

    ports:
      - "5501:5001"

    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: productsdb
      REDIS_HOST: redis

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    restart: always

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5001/products?page=1"]
      interval: 30s
      timeout: 10s
      retries: 3



  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    container_name: api-gateway

    ports:
      - "8080:8080"

    depends_on:
      - auth-service
      - product-service

    restart: always

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3



volumes:
  postgres-data:
  redis-data:
